import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum nam quasi recusandae autem maiores veritatis ut ad aspernatur id suscipit.
        </p>
      </main>
    </>
  )
}

export default Home